name:                teststack
version:             0.1.0.0
github:              "zubairabid/teststack"
license:             BSD3
author:              "Zubair Abid"
maintainer:          "zubairabid1999+github@gmail.com"
copyright:           "2018 Zubair Abid"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zubairabid/teststack#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  teststack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - teststack

tests:
  teststack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - teststack
